### ISSUE TITLE
 SSD1306_DrawPixel parameter check.

### ISSUE THREAD

**Issue by bpringlemeir** [Matiasus/SSD1306#10]
https://github.com/Matiasus/SSD1306/blob/ce135fab47cd65dc58a2df5739a3c595ce4bb8b9/lib/ssd1306.c#L522

I think there is an issue with the parameter checking in this routine?

```
  if ((x > MAX_X) && (y > MAX_Y)) {
    // out of range
    return SSD1306_ERROR;
  }
```
It should be '||' as we need both parameters to be in range?

**Comment by Matiasus** [comment]
Hi Bill,

Yes, You're right, I'm going to change it.
Thanks a lot.

Best regards
Marián

st 14. 6. 2023 o 17:35 Bill Pringlemeir ***@***.***>
napísal(a):

**Comment by Matiasus** [comment]
Changed.
