### ISSUE TITLE
Data Memory Usage

### ISSUE THREAD

**Issue by mikailylk** [Matiasus/SSD1306#7]
I use ATMEGA328P and when I build the application, it uses about 1000Bytes Data Memory (~50%). I would like to ask you, if I do something wrong or is that (SSD-LIB) usually that big (DATA Memory Usage).

Kind Regards

**Comment by Matiasus** [comment]
Yes your right, the RAM consumption is considerable (~1kB), but I created new lightweight version [v3.0.0](https://github.com/Matiasus/SSD1306/releases/tag/v3.0.0) for displaying only alphanumeric characters without drawing lines or pixels. You can try to test it.

Kind Regards

**Comment by Matiasus** [comment]
Int the comment above.
