### ISSUE TITLE
128x32 OLED display

### ISSUE THREAD

**Issue by vojt444** [Matiasus/SSD1306#8]

**Comment by Matiasus** [comment]
Hello,

you should change following parameter in *ssd1306.h*

   - END_PAGE_ADDR from 7 to 3 // 7 for 128x64 version, 3 for 128x32 version

and parameters in *ssd1306.c*

   - SSD1306_SET_MUX_RATIO from 0x3F to 0x1F //  // 0x3F (64MUX) for 128x64
   version, 0x1F (32MUX) for 128x32 version
   - SSD1306_COM_PIN_CONF from 0x12 to 0x02 // disable COM Left/Right
   remap, disable alternative COM pin configuration

Hope that helps.

Kind regards

MH

so 19. 11. 2022 o 17:03 vojt444 ***@***.***> napísal(a):
