### ISSUE TITLE
How can use this library with atmega128?

### ISSUE THREAD

**Issue by SahanGura** [Matiasus/SSD1306#9]
Could you please mention the necessary changes need to be done for using this library with atmega 128 chip?

**Comment by Matiasus** [comment]
The library is intended for the use of Atmega8, Atmega328p, Atmega16 microcontrollers, on which I can test the functionality, but with small modifications (especially the correct setting of the I2C pins SDA, SCL and the frequency setting in TWBR) it could also work with the Atmega128. Unfortunately, I cannot test the functionality of the ATmega128 chip.
